"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import {
  ArrowRight, BookOpen, Bot, Brain, CalendarDays, Check, CheckCircle2,
  ChevronDown, ChevronLeft, Code2, Home, Lightbulb, MoreHorizontal, Play,
  Search, Sparkles, Target, Trophy, UserRound, UsersRound
} from "lucide-react";

type Screen = "landing"|"assessment"|"profile"|"path"|"today"|"coach"|"projects"|"parent";
const nav: Record<Screen,string> = {
  landing:"/prototype/landing", assessment:"/prototype/assessment", profile:"/prototype/profile",
  path:"/prototype/path", today:"/prototype/today", coach:"/prototype/coach",
  projects:"/prototype/projects", parent:"/prototype/parent"
};

function Logo(){return <div className="c3-logo" aria-label="3C"><span>3</span><span>C</span></div>}
function Avatar({kind="kid"}:{kind?:"kid"|"parent"|"teacher"}){const g=kind==="parent"?"👩🏻":kind==="teacher"?"👨🏻‍🏫":"👦🏻";return <span className={`avatar avatar-${kind}`} aria-hidden="true">{g}</span>}
function StatusBar(){return <div className="status-bar"><span>9:41</span><div><span>▮▮▮</span><span>⌁</span><span>▰</span></div></div>}
function BottomNav({screen}:{screen:Screen}){return <nav className="bottom-nav"><Link href={nav.today} className={screen==="today"?"active":""}><Home/><span>Home</span></Link><Link href={nav.path} className={screen==="path"?"active":""}><BookOpen/><span>Learn</span></Link><Link href={nav.projects} className={screen==="projects"?"active":""}><Trophy/><span>Projects</span></Link><Link href={nav.profile} className={screen==="profile"?"active":""}><UsersRound/><span>Community</span></Link><Link href={nav.parent} className={screen==="parent"?"active":""}><MoreHorizontal/><span>More</span></Link></nav>}
function Phone({screen,children,navBar=true}:{screen:Screen;children:React.ReactNode;navBar?:boolean}){return <main className="demo-page"><div className="phone"><div className="notch"/><StatusBar/><div className="phone-body">{children}</div>{navBar&&screen!=="landing"&&screen!=="assessment"&&screen!=="coach"&&<BottomNav screen={screen}/>}</div></main>}
function Skill({label,value,delta,color="#1f78ff"}:{label:string;value:number;delta?:string;color?:string}){return <div className="skill-row"><div className="skill-label"><span>{label}</span><div><b>{value}%</b>{delta&&<em>{delta}</em>}</div></div><div className="skill-track"><i style={{width:`${value}%`,background:color}}/></div></div>}
function TopTitle({title,back,avatar}:{title:string;back?:string;avatar?:boolean}){return <header className="screen-title">{back?<Link href={back} className="back-btn"><ChevronLeft/></Link>:<span className="title-spacer"/>}<h1>{title}</h1>{avatar?<Avatar/>:<span className="title-spacer"/>}</header>}

export default function PrototypeScreen({screen}:{screen:Screen}){
  const router=useRouter();
  const [assessmentStep,setAssessmentStep]=useState(1);
  const [age,setAge]=useState("9-12");
  const [interests,setInterests]=useState<string[]>(["games","ai","python"]);
  const [device,setDevice]=useState("yes");
  const [coachText,setCoachText]=useState("Great start! I can see you’re working on a dictionary.\n\nDo you want a hint, an explanation, or a similar example?");
  const [question,setQuestion]=useState("");
  const [projectFilter,setProjectFilter]=useState<"all"|"progress"|"completed">("all");
  const [pathTab,setPathTab]=useState<"levels"|"courses"|"achievements">("levels");
  const [toast,setToast]=useState("");
  const toggleInterest=(v:string)=>setInterests(p=>p.includes(v)?p.filter(x=>x!==v):(p.length<3?[...p,v]:p));
  const projects=useMemo(()=>[
    {id:1,status:"progress",title:"Space Adventure",sub:"A 2D game built with Pygame",emoji:"🚀",tag:"In Progress"},
    {id:2,status:"completed",title:"AI Image Classifier",sub:"Using Teachable Machine",emoji:"🤖",tag:"Completed"},
    {id:3,status:"completed",title:"My First Website",sub:"HTML, CSS, JavaScript",emoji:"🌐",tag:"Completed"},
    {id:4,status:"new",title:"Calculator App",sub:"Python (Tkinter)",emoji:"🧮",tag:"Not Started"}
  ].filter(p=>projectFilter==="all"||(projectFilter==="progress"&&p.status==="progress")||(projectFilter==="completed"&&p.status==="completed")),[projectFilter]);
  const notify=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(""),1800)};

  if(screen==="landing")return <Phone screen={screen} navBar={false}><section className="landing-screen"><div className="landing-top"><Logo/><button type="button" className="lang-btn" onClick={()=>notify("Arabic experience is available")}>🌐 EN</button></div><div className="landing-copy"><h1>A Brighter<br/>Future Starts<br/>Here</h1><p>Live online coding & AI classes<br/>for kids aged 6–18.</p></div><div className="hero-kids"><div className="shape shape-a">⌘</div><div className="shape shape-b">⌁</div><div className="shape shape-c">★</div><div className="kid kid-left">👦🏻</div><div className="kid kid-main">🧑🏻‍💻</div><div className="kid kid-right">👧🏻</div><div className="hoodie-logo"><Logo/></div></div><div className="landing-cta"><Link href={nav.assessment} className="blue-btn">Start Your Journey <ArrowRight/></Link></div><div className="landing-stats"><div><b>120K+</b><span>Students</span></div><div><b>4.8 ⭐</b><span>Parent Rating</span></div><div><b>Egypt • UAE<br/>KSA • Oman</b><span>Countries</span></div></div>{toast&&<div className="toast">{toast}</div>}</section></Phone>;

  if(screen==="assessment")return <Phone screen={screen} navBar={false}><section className="assessment-screen"><div className="assessment-head"><Link href={nav.landing}><ChevronLeft/></Link><Bot/></div><h1>Let&apos;s get to know<br/>your child</h1><div className="assessment-progress"><i style={{width:`${assessmentStep*25}%`}}/><span>{assessmentStep}/4</span></div>{assessmentStep===1&&<><h2>What is your child&apos;s age?</h2><div className="age-grid">{["6-8","9-12","13-15","16-18"].map(v=><button key={v} onClick={()=>setAge(v)} className={age===v?"selected":""}>{v}</button>)}</div><h2>What are they interested in? <small>(Choose up to 3)</small></h2><div className="interest-grid">{[["games","🎮","Games"],["ai","🤖","AI & Robots"],["web","🖥️","Web"],["mobile","📱","Mobile Apps"],["design","🚀","Design"],["python","📊","Data Science"]].map(([id,ico,label])=><button key={id} onClick={()=>toggleInterest(id)} className={interests.includes(id)?"selected":""}><span>{ico}</span><b>{label}</b>{interests.includes(id)&&<CheckCircle2/>}</button>)}</div><h2>Do they have a laptop/PC/tablet?</h2><div className="segmented two"><button onClick={()=>setDevice("yes")} className={device==="yes"?"active":""}>Yes</button><button onClick={()=>setDevice("not-yet")} className={device==="not-yet"?"active":""}>Not yet</button></div></>}{assessmentStep===2&&<div className="step-card"><Brain/><h2>How do they usually solve a new problem?</h2><div className="choice-stack">{["I try different ideas","I ask for help quickly","I watch an example first"].map((x,i)=><button key={x} className={i===0?"selected":""}>{x}</button>)}</div></div>}{assessmentStep===3&&<div className="step-card"><Code2/><h2>Have they coded before?</h2><div className="choice-stack">{["Never","Scratch / block coding","Python or text-based coding"].map((x,i)=><button key={x} className={i===1?"selected":""}>{x}</button>)}</div></div>}{assessmentStep===4&&<div className="step-card final-step"><Sparkles/><h2>Perfect — we have enough to build Youssef&apos;s starting profile.</h2><p>We&apos;ll recommend a path based on age, interests, and current experience.</p></div>}<button className="blue-btn assessment-next" onClick={()=>assessmentStep<4?setAssessmentStep(assessmentStep+1):router.push(nav.profile)}>Next <ArrowRight/></button></section></Phone>;

  if(screen==="profile")return <Phone screen={screen}><section className="profile-screen"><TopTitle title="Here’s Youssef’s Learning Profile!" avatar/><p className="subhead">Based on our smart assessment, we recommend the following track.</p><div className="profile-identity"><Avatar/><div><b>Youssef</b><span>11 years old</span><em>Explorer 🚀</em></div><Link href={nav.assessment}>✎ Edit</Link></div><div className="card skill-card"><h2>Skill Snapshot</h2><Skill label="Logical Thinking" value={88} color="#19bf7f"/><Skill label="Creativity" value={92} color="#a737e8"/><Skill label="Problem Solving" value={71} color="#f3a61f"/><Skill label="Coding Basics" value={64} color="#187cff"/><Skill label="AI Concepts" value={35} color="#e94d84"/><h3>Top Interests</h3><div className="chips"><span>Games</span><span>AI</span><span>Python</span></div></div><div className="card recommended-card"><div className="rec-icon">🧭</div><div><small>Recommended Track</small><h2>Python & Game Development</h2><p>A great fit for Youssef&apos;s interests and skills.</p></div></div><Link className="blue-btn" href={nav.path}>View Learning Path <ArrowRight/></Link></section></Phone>;

  if(screen==="path")return <Phone screen={screen}><section className="path-screen"><TopTitle title="My Learning Path" avatar/><button className="track-select" onClick={()=>notify("Track selector opened")}>Python Track <ChevronDown/></button><div className="tabs">{(["levels","courses","achievements"] as const).map(t=><button key={t} className={pathTab===t?"active":""} onClick={()=>setPathTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>{pathTab==="levels"&&<div className="level-list"><div className="level-item done"><div className="level-dot"><Check/></div><div><span>Level 1</span><h2>Python Basics</h2><b>Completed</b><small>12 lessons • 3 projects</small></div></div><div className="level-item current"><div className="level-dot">2</div><div><span>Level 2</span><h2>Intermediate Python</h2><b>In Progress</b><small>6/13 lessons</small></div></div><div className="level-item locked"><div className="level-dot">3</div><div><span>Level 3</span><h2>Game Development</h2><b>Locked</b></div></div><div className="level-item locked"><div className="level-dot">4</div><div><span>Level 4</span><h2>Advanced Python</h2><b>Locked</b></div></div></div>}{pathTab==="courses"&&<div className="simple-list"><div>📘 Dictionaries & Sets <b>Today</b></div><div>🧩 Functions <b>Next</b></div><div>🎮 Pygame Basics <b>Locked</b></div></div>}{pathTab==="achievements"&&<div className="achievement-grid"><span>🏅 Python Starter</span><span>🔥 7 Day Streak</span><span>🧠 Logic Pro</span><span>🚀 Project Builder</span></div>}<div className="whats-next"><small>What&apos;s next?</small><h3>👜 Lesson 7: Dictionaries</h3><p>Today • 5:00 PM</p><Link href={nav.today} className="blue-btn">Join Class</Link></div>{toast&&<div className="toast">{toast}</div>}</section></Phone>;

  if(screen==="today")return <Phone screen={screen}><section className="today-screen"><TopTitle title="Today’s Mission" avatar/><div className="keep-going"><div><b>Keep going, Youssef! 🔥</b><span>You&apos;re 2 classes away from completing Level 2!</span></div><span className="flame">🔥</span></div><div className="mission-card"><div className="mission-label"><span>▣ Live Class</span><em>In 2 hours</em></div><h2>Intermediate Python</h2><p>Dictionaries & Sets</p><div className="meta-line">🕔 5:00 – 6:00 PM</div><div className="teacher-line"><Avatar kind="teacher"/> Mr. Ahmed</div><button className="blue-btn" onClick={()=>notify("Joining live class…")}>Join Class</button></div><div className="mission-card practice"><div className="mission-label"><span>▣ Practice</span></div><div className="mini-challenge"><div className="challenge-icon">🏅</div><div><b>Mini Challenge</b><span>Work with dictionaries</span></div><Link href={nav.coach} className="round-play"><Play/></Link></div><div className="challenge-meta"><span>◷ 15 min</span><span>+30 XP</span></div></div><div className="mission-card project-mission"><div className="mission-label"><span>▣ Project Studio</span></div><Link href={nav.projects}><div className="challenge-icon orange">🧩</div><div><b>Build a Simple Calculator</b><span>Continue your project</span></div><em>+50 XP</em></Link></div>{toast&&<div className="toast">{toast}</div>}</section></Phone>;

  if(screen==="coach")return <Phone screen={screen} navBar={false}><section className="coach-screen"><header className="coach-header"><Link href={nav.today}><ChevronLeft/></Link><h1>AI Coding Coach</h1><Bot/></header><div className="coach-bubble"><Bot/><p>{coachText}</p></div><pre className="code-block" dir="ltr">{`student = {\n  "name": "Youssef",\n  "age": 11\n}\n\nprint(student["name"])\nprint(student["ag"])`}</pre><div className="issue-box"><b>⚠ There&apos;s a small issue!</b><p>Did you mean <code>&quot;age&quot;</code> instead of <code>&quot;ag&quot;</code> ?</p></div><div className="coach-action-list"><button onClick={()=>setCoachText("Hint: compare the key in the last line with the keys inside the dictionary. 👀")}><Lightbulb/>Give me a hint</button><button onClick={()=>setCoachText("A Python dictionary stores values by exact keys. If the key is 'age', asking for 'ag' will fail.")}><BookOpen/>Explain this concept</button><button onClick={()=>setCoachText("Similar example: user = {'name':'Ali'} then print(user['name']). Now try the same pattern.")}><UserRound/>Show similar example</button></div><form className="coach-input" onSubmit={e=>{e.preventDefault();if(question.trim()){setCoachText(`Good question. Let’s work through “${question.trim()}” step by step without giving away the answer.`);setQuestion("")}}}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Type your question..."/><button aria-label="Send"><ArrowRight/></button></form></section></Phone>;

  if(screen==="projects")return <Phone screen={screen}><section className="projects-screen"><TopTitle title="My Projects"/><button className="search-icon" onClick={()=>notify("Project search opened")}><Search/></button><div className="tabs project-tabs"><button className={projectFilter==="all"?"active":""} onClick={()=>setProjectFilter("all")}>All</button><button className={projectFilter==="progress"?"active":""} onClick={()=>setProjectFilter("progress")}>In Progress</button><button className={projectFilter==="completed"?"active":""} onClick={()=>setProjectFilter("completed")}>Completed</button></div><div className="project-list">{projects.map(p=><article className="project-card" key={p.id}><div className={`project-thumb thumb-${p.id}`}><span>{p.emoji}</span>{p.id===1&&<div className="pixel-world">⭐ 🛸 🪐</div>}</div><div className="project-copy"><b>{p.title}</b><span>{p.sub}</span><div><em className={`status-${p.status}`}>{p.tag}</em>{p.status==="completed"&&<button onClick={()=>notify(`${p.title} opened`)}>View Project</button>}</div></div></article>)}</div><button className="new-project-btn" onClick={()=>notify("New project template created")}>+ New Project</button>{toast&&<div className="toast">{toast}</div>}</section></Phone>;

  return <Phone screen="parent"><section className="parent-screen"><TopTitle title="Parent Dashboard"/><Avatar kind="parent"/><button className="month-select" onClick={()=>notify("Month selector opened")}>This Month <ChevronDown/></button><div className="parent-card"><div className="parent-profile"><Avatar/><b>Yousseff&apos;s Progress</b></div><div className="parent-metrics"><div><b>92%</b><span>Attendance</span></div><div><b>12h 30m</b><span>Learning Time</span></div><div><b>+18%</b><span>Skills Growth</span></div></div></div><div className="parent-card skills-parent"><div className="section-line"><h2>Skill Development</h2><span>This Month⌄</span></div><Skill label="Logical Thinking" value={88} delta="+6%"/><Skill label="Python" value={64} delta="+12%"/><Skill label="Problem Solving" value={71} delta="+9%"/><Skill label="Creativity" value={92} delta="+4%"/><Skill label="AI Concepts" value={35} delta="+15%"/></div><div className="ai-insight"><Sparkles/><div><b>AI Insight</b><p>Youssef shows great creativity! We recommend encouraging him with more game development projects.</p></div></div><div className="upcoming"><h2>Upcoming</h2><Link href={nav.path}><CalendarDays/><div><b>Level 2 Completion</b><span>2 classes left</span></div><ChevronLeft/></Link></div>{toast&&<div className="toast">{toast}</div>}</section></Phone>;
}
