"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, BarChart3, Bot, Brain, CheckCircle2, Code2, Gamepad2, Home, Lightbulb, LockKeyhole, Rocket, Sparkles, Target, Trophy, UserRound } from "lucide-react";

type Screen = "landing"|"assessment"|"profile"|"path"|"today"|"coach"|"projects"|"parent";
const validScreens: Screen[] = ["landing","assessment","profile","path","today","coach","projects","parent"];
const nav: Record<Screen,string> = { landing:"/prototype/landing", assessment:"/prototype/assessment", profile:"/prototype/profile", path:"/prototype/path", today:"/prototype/today", coach:"/prototype/coach", projects:"/prototype/projects", parent:"/prototype/parent" };

function Logo(){return <div className="app-logo" aria-label="3C"><b>3</b><b>C</b></div>}
function Skill({label,value}:{label:string;value:number}){return <div className="skill"><div><span>{label}</span><b>{value}%</b></div><div className="skillbar"><i style={{width:`${value}%`}}/></div></div>}
function Shell({screen,children}:{screen:Screen;children:React.ReactNode}){
  const labels=["الرئيسية","التقييم","ملف المتعلم","المسار","مهام اليوم","المساعد الذكي","المشاريع","ولي الأمر"];
  return <main className="app-page"><div className="app-device"><div className="app-notch"/><div className="app-content">{children}</div>{screen!=="landing"&&screen!=="assessment"&&<nav className="app-nav"><Link className={screen==="today"?"active":""} href={nav.today}><Home/><span>الرئيسية</span></Link><Link className={screen==="path"?"active":""} href={nav.path}><Target/><span>المسار</span></Link><Link className={screen==="projects"?"active":""} href={nav.projects}><Trophy/><span>المشاريع</span></Link><Link className={screen==="parent"?"active":""} href={nav.parent}><UserRound/><span>ولي الأمر</span></Link></nav>}</div><div className="screen-map">{validScreens.map((s,i)=><Link key={s} href={nav[s]} className={screen===s?"active":""}><span>{i+1}</span>{labels[i]}</Link>)}</div></main>
}

export default function PrototypeScreen({screen}:{screen:Screen}){
  const router=useRouter(); const [step,setStep]=useState(1); const [age,setAge]=useState("9-12"); const [interest,setInterest]=useState("games"); const [level,setLevel]=useState("basic"); const [coach,setCoach]=useState("لاحظت خطأ بسيط 👀 — اسم المفتاح في السطر الأخير لا يطابق المفتاح الموجود في القاموس.");
  const track=useMemo(()=>({games:"Python + تطوير الألعاب",ai:"Python + الذكاء الاصطناعي",web:"Python + تطوير الويب",data:"Python + تحليل البيانات"} as Record<string,string>)[interest],[interest]);
  if(screen==="landing") return <Shell screen={screen}><section className="landing"><div className="landing-art"><Image src="/3c-concept-ar.jpg" alt="تصور 3C العربي" fill priority sizes="430px"/><div className="art-shade"/><div className="top-mini"><span className="lang">AR</span><Logo/></div><div className="hero-copy"><span className="kicker">3C Online Coding School</span><h1>مستقبل أفضل<br/>يبدأ من هنا</h1><p>تجربة تعلم مخصصة في البرمجة والذكاء الاصطناعي للأطفال من 6 إلى 18 سنة.</p></div></div><div className="landing-body"><div className="metric-row"><div><b>+120K</b><span>طالب وطالبة</span></div><div><b>4.8★</b><span>تقييم أولياء الأمور</span></div><div><b>6–18</b><span>سنة</span></div></div><div className="feature-row"><span><Code2/>Live Coding</span><span><Gamepad2/>مشاريع</span><span><Brain/>AI & ML</span></div><Link className="primary" href={nav.assessment}>ابدأ رحلة طفلك <ArrowLeft/></Link><div className="sub-note">Prototype مقترح لتطوير تجربة 3C الحالية</div></div></section></Shell>;
  if(screen==="assessment"){
    const groups=[{title:"ما عمر طفلك؟",sub:"نستخدم العمر لتخصيص مستوى التحدي",opts:[["6-8","6–8"],["9-12","9–12"],["13-15","13–15"],["16-18","16–18"]],v:age,set:setAge},{title:"ما أكثر مجال يحمّسه؟",sub:"يمكن تغيير المسار لاحقًا",opts:[["games","🎮 الألعاب"],["ai","🤖 الذكاء الاصطناعي"],["web","🌐 المواقع"],["data","📊 البيانات"]],v:interest,set:setInterest},{title:"ما خبرته الحالية؟",sub:"لن نبدأ من الصفر إذا كان لديه أساس جيد",opts:[["new","مبتدئ تمامًا"],["basic","Scratch / أساسيات"],["intermediate","Python / مشاريع"]],v:level,set:setLevel}]; const g=groups[step-1];
    return <Shell screen={screen}><section className="pad"><header className="app-head"><button onClick={()=>step>1?setStep(step-1):router.push(nav.landing)}><ArrowRight/></button><div><b>التقييم الذكي</b><span>بناء نقطة بداية مخصصة</span></div><Logo/></header><div className="step-line"><i style={{width:`${step*33.33}%`}}/><span>{step}/3</span></div><div className="bot-card"><Bot/><div><b>خلّيني أتعرف على طفلك 👋</b><span>الإجابة لا تستغرق أكثر من دقيقة</span></div></div><h2 className="q-title">{g.title}</h2><p className="muted">{g.sub}</p><div className="choices">{g.opts.map(([v,l])=><button className={g.v===v?"selected":""} onClick={()=>g.set(v)} key={v}>{g.v===v&&<CheckCircle2/>}<span>{l}</span></button>)}</div><button className="primary" onClick={()=>step<3?setStep(step+1):router.push(`${nav.profile}?track=${interest}`)}>{step<3?"التالي":"أنشئ ملف المتعلم"} <ArrowLeft/></button></section></Shell>;
  }
  if(screen==="profile") return <Shell screen={screen}><section className="pad"><header className="app-head"><Link href={nav.assessment}><ArrowRight/></Link><div><b>مرحبًا يوسف! 👋</b><span>هذا ملفك التعليمي المبدئي</span></div><Logo/></header><div className="profile-card"><div className="avatar">ي</div><div><b>يوسف • 11 سنة</b><span>Explorer 🚀</span></div><Link href={nav.assessment}>تعديل</Link></div><div className="section-title"><span>نقاط القوة</span><Brain/></div><div className="skills"><Skill label="التفكير المنطقي" value={88}/><Skill label="الإبداع" value={92}/><Skill label="حل المشكلات" value={71}/><Skill label="أساسيات البرمجة" value={64}/><Skill label="مفاهيم الذكاء الاصطناعي" value={35}/></div><div className="recommend"><Target/><div><span>المسار المقترح</span><b>Python + تطوير الألعاب</b><small>بناءً على العمر والاهتمامات والمهارات</small></div></div><Link className="primary" href={nav.path}>عرض المسار المقترح <ArrowLeft/></Link></section></Shell>;
  if(screen==="path") return <Shell screen={screen}><section className="pad"><header className="app-head"><Link href={nav.profile}><ArrowRight/></Link><div><b>مساري التعليمي</b><span>Python Track</span></div><Logo/></header><div className="ai-note"><Sparkles/><div><b>AI حدّث خطتك</b><span>أضفنا تدريبًا إضافيًا على حل المشكلات بناءً على أدائك.</span></div></div><div className="timeline"><div className="level done"><i>✓</i><div><span>المستوى 1</span><b>أساسيات Python</b><small>مكتمل • 12 درسًا • 3 مشاريع</small></div></div><div className="level current"><i>2</i><div><span>المستوى 2</span><b>Python المتوسط</b><small>6/13 جلسة • قيد التعلم</small><div className="mini-bar"><em/></div></div></div><div className="level"><i><LockKeyhole/></i><div><span>المستوى 3</span><b>تطوير الألعاب</b><small>يفتح بعد المستوى الحالي</small></div></div><div className="level"><i><LockKeyhole/></i><div><span>المستوى 4</span><b>الذكاء الاصطناعي المتقدم</b><small>AI & Machine Learning</small></div></div></div><div className="next-card"><span>الدرس القادم</span><b>القواميس والمجموعات</b><small>اليوم • 5:00 مساءً</small><Link href={nav.today}>اذهب لمهام اليوم <ArrowLeft/></Link></div></section></Shell>;
  if(screen==="today") return <Shell screen={screen}><section className="pad"><header className="app-head"><span/><div><b>مهامي اليوم</b><span>الأحد 7 سبتمبر</span></div><Logo/></header><div className="streak"><div><b>🔥 استمر يا يوسف!</b><span>أنت على بعد حصتين من إكمال المستوى 2</span></div><strong>7 أيام</strong></div><div className="task live"><span>حصة مباشرة • بعد ساعتين</span><b>Python المتوسط</b><small>القواميس والمجموعات • 5:00 – 6:00 م</small><button onClick={()=>alert("تم فتح تجربة الحصة المباشرة")}>الانضمام للحصة</button></div><div className="task"><span>تدريب • +10 نقاط</span><b>مراجعة القواميس</b><small>15 دقيقة</small><Link href={nav.coach}>ابدأ مع المساعد الذكي <ArrowLeft/></Link></div><div className="task"><span>مشروع • +50 XP</span><b>لعبة مغامرة فضائية</b><small>تابع مشروعك الحالي</small><Link href={nav.projects}>فتح المشروع <ArrowLeft/></Link></div></section></Shell>;
  if(screen==="coach") return <Shell screen={screen}><section className="pad"><header className="app-head"><Link href={nav.today}><ArrowRight/></Link><div><b>مساعد 3C الذكي</b><span>يدعم التعلم بدل إعطاء الإجابة</span></div><Bot/></header><div className="coach-msg"><Bot/><p>{coach}</p></div><pre className="code" dir="ltr">{`student = {\n  "name": "Youssef",\n  "age": 11\n}\n\nprint(student["ag"])`}</pre><div className="coach-actions"><button onClick={()=>setCoach('تلميح: قارن كلمة "ag" بالمفاتيح الموجودة داخل القاموس 👀')}><Lightbulb/>أعطني تلميحًا</button><button onClick={()=>setCoach("في Python، القاموس يخزن البيانات كـ Key وValue. يجب استخدام اسم الـKey نفسه تمامًا.")}><Brain/>اشرح لي المفهوم</button><button onClick={()=>setCoach("مثال: user = {'name':'Ali'} ثم print(user['name']). حاول تطبيق نفس الفكرة.")}><Code2/>أعطني مثالًا مشابهًا</button></div><Link className="primary" href={nav.projects}>تم الحل — تابع للمشروع <ArrowLeft/></Link></section></Shell>;
  if(screen==="projects") return <Shell screen={screen}><section className="pad"><header className="app-head"><Link href={nav.today}><ArrowRight/></Link><div><b>استوديو المشاريع</b><span>Portfolio حقيقي للمتعلم</span></div><Rocket/></header><div className="project hero-project"><div className="project-img"><Image src="/3c-concept-ar.jpg" alt="" fill sizes="390px"/></div><div><span>قيد العمل • 60%</span><b>🚀 لعبة مغامرة فضائية</b><small>Pygame • Game Development</small><div className="mini-bar"><em style={{width:"60%"}}/></div><button onClick={()=>alert("تم فتح المرحلة التالية من المشروع")}>متابعة المشروع</button></div></div><div className="project"><div><span>مكتمل ✓</span><b>🤖 مصنف الصور بالذكاء الاصطناعي</b><small>Teachable Machine</small></div></div><div className="project"><div><span>مكتمل ✓</span><b>🌐 موقعي الأول</b><small>HTML • CSS • JavaScript</small></div></div><Link className="primary" href={nav.parent}>عرض النتائج لولي الأمر <ArrowLeft/></Link></section></Shell>;
  return <Shell screen="parent"><section className="pad"><header className="app-head"><Link href={nav.projects}><ArrowRight/></Link><div><b>لوحة ولي الأمر</b><span>تقدم يوسف • هذا الشهر</span></div><Logo/></header><div className="parent-metrics"><div><b>92%</b><span>الحضور</span></div><div><b>12س 30د</b><span>وقت التعلم</span></div><div><b>+18%</b><span>نمو المهارات</span></div></div><div className="section-title"><span>تطور المهارات</span><BarChart3/></div><div className="skills"><Skill label="التفكير المنطقي" value={88}/><Skill label="Python" value={64}/><Skill label="حل المشكلات" value={71}/><Skill label="الإبداع" value={92}/><Skill label="مفاهيم الذكاء الاصطناعي" value={35}/></div><div className="parent-insight"><Sparkles/><div><b>رؤية الذكاء الاصطناعي</b><p>يوسف يظهر إبداعًا قويًا وتقدمًا ملحوظًا في التفكير المنطقي. نوصي بزيادة مشاريع تطوير الألعاب خلال الشهر القادم.</p></div></div><Link className="primary" href={nav.landing}>إعادة تجربة الرحلة <ArrowLeft/></Link></section></Shell>;
}
