"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";

type Screen = "landing"|"assessment"|"profile"|"path"|"today"|"coach"|"projects"|"parent";

const labels = {
  en:{home:"Home",learn:"Learn",projects:"Projects",coach:"Coach",more:"More"},
  ar:{home:"الرئيسية",learn:"تعلم",projects:"مشاريعي",coach:"المساعد",more:"المزيد"}
};

function Nav({active,lang}:{active:Screen,lang:"ar"|"en"}){
  const l=labels[lang];
  const items:[Screen,string,string][]=[
    ["today","⌂",l.home],["path","▣",l.learn],["projects","▱",l.projects],["coach","◯",l.coach],["parent","•••",l.more]
  ];
  return <nav className="ref-bottomnav">{items.map(([id,ic,tx])=><Link key={id} className={active===id?"on":""} href={`/prototype/${id}?lang=${lang}`}><b>{ic}</b><span>{tx}</span></Link>)}</nav>
}
function Status(){return <div className="ref-status"><span>9:41</span><span>▰ ◔ ▮▮▮</span></div>}
function Avatar({type="boy"}:{type?:"boy"|"girl"|"teacher"}){return <span className="ref-avatar">{type==="girl"?"👩🏻":type==="teacher"?"👨🏻‍🏫":"👦🏻"}</span>}
function Shell({children,active,lang}:{children:React.ReactNode,active:Screen,lang:"ar"|"en"}){return <main className="ref-page" dir={lang==="ar"?"rtl":"ltr"}><div className="ref-device"><div className="ref-bezel"><div className="ref-notch"/><Status/><div className="ref-screen">{children}</div>{active!=="landing"&&active!=="assessment"&&<Nav active={active} lang={lang}/>}</div></div></main>}
function LangBtn({lang}:{lang:"ar"|"en"}){return <Link className="ref-lang" href={`?lang=${lang==="ar"?"en":"ar"}`}>🌐 {lang==="ar"?"EN":"AR"}</Link>}

function Landing({lang}:{lang:"ar"|"en"}){const ar=lang==="ar";return <div className="ref-content ref-pad ref-landing">
  <div className="ref-between"><div className="ref-logo">3C</div><LangBtn lang={lang}/></div>
  <h1>{ar?"مستقبل أفضل ":"A Brighter Future "}<span>{ar?"يبدأ من هنا":"Starts Here"}</span></h1>
  <p>{ar?"دورات برمجة وذكاء اصطناعي مباشرة أونلاين للأطفال من 6 إلى 18 سنة.":"Live online coding & AI classes for kids aged 6–18."}</p>
  <div className="ref-stats"><div>🎓<b>120K+</b><small>{ar?"طالب":"Students"}</small></div><i/><div>⭐<b>4.8</b><small>{ar?"تقييم الأهل":"Parent Rating"}</small></div><i/><div>🌐<b className="countries">{ar?"مصر·الإمارات\nالسعودية·عُمان":"Egypt·UAE\nKSA·Oman"}</b></div></div>
  <div className="ref-hero3d"><img src="/hero-kids-final.webp" alt="3C kids learning to code"/></div>
  <Link className="ref-primary" href={`/prototype/assessment?lang=${lang}`}>{ar?"ابدأ رحلتك الآن":"Start Your Journey"} →</Link>
  <div className="ref-card ref-tracks"><div>🎮 <b>{ar?"تطوير الألعاب":"Game Development"}</b></div><div>🤖 <b>{ar?"الذكاء والروبوتات":"AI & Robotics"}</b></div><div>🌐 <b>{ar?"تطوير المواقع":"Web Development"}</b></div><div>📊 <b>{ar?"التطبيقات والتصميم":"Apps & Design"}</b></div></div>
  <div className="ref-card ref-community"><div className="ref-stack"><Avatar/><Avatar type="girl"/><Avatar type="teacher"/></div><div><b>{ar?"انضم لـ 120,000+":"Join 120,000+"}</b><small>{ar?"متعلم يبنون مستقبلهم مع 3C":"learners building their future with 3C"}</small></div><button>▶ <span>{ar?"شاهد\nقصتنا":"Watch\nOur Story"}</span></button></div>
  <div className="ref-scroll">⌄ {ar?"مرّر للاستكشاف":"Scroll to explore"}</div>
</div>}

function Profile({lang}:{lang:"ar"|"en"}){const ar=lang==="ar";const skills=[[ar?"التفكير المنطقي":"Logical Thinking",88,"#28c98c"],["Python",92,"#8b3df0"],[ar?"حل المشكلات":"Problem Solving",71,"#f3a72e"],[ar?"أساسيات البرمجة":"Coding Basics",64,"#278ef7"],[ar?"مفاهيم الذكاء الاصطناعي":"AI Concepts",35,"#f34f85"]] as const;return <div className="ref-content ref-pad">
  <div className="ref-head"><Avatar/><div><h2>{ar?"ملفك التعليمي يا يوسف 🎉":"Youssef's Learning Profile 🎉"}</h2><p>{ar?"بناءً على التقييم الذكي، نرشّح لك المسار التالي.":"Based on our smart assessment, we recommend the following track."}</p></div></div>
  <div className="ref-profile-identity"><Avatar/><div><b>{ar?"يوسف":"Youssef"}</b><small>{ar?"11 سنة · مستكشف":"11 yrs · Explorer"}</small></div><button>{ar?"تعديل":"Edit"}</button></div>
  <div className="ref-card ref-skills"><h3>{ar?"نقاط القوة":"Strengths"}</h3>{skills.map(([n,p,c])=><div className="ref-skill" key={n}><span>{n}</span><div><i style={{width:`${p}%`,background:c}}/></div><b>{p}%</b></div>)}<h4>{ar?"أبرز الاهتمامات":"Top Interests"}</h4><div className="ref-chips"><span>{ar?"الألعاب":"Games"}</span><span>{ar?"الذكاء":"AI"}</span><span>Python</span></div></div>
  <div className="ref-card ref-recommend"><small>{ar?"🎯 المسار المقترح":"🎯 Recommended track"}</small><h3>{ar?"Python وتطوير الألعاب":"Python & Game Development"}</h3><p>{ar?"مسار يناسب اهتمامات يوسف وسرعة تعلمه.":"A track tailored to Youssef's interests and learning pace."}</p></div>
  <Link className="ref-primary" href={`/prototype/path?lang=${lang}`}>{ar?"عرض المسار التعليمي":"View Learning Path"} →</Link>
</div>}

function Path({lang}:{lang:"ar"|"en"}){const ar=lang==="ar";const levels=[["✓",ar?"المستوى 1 · أساسيات بايثون":"Level 1 · Python Basics",ar?"مكتمل":"Complete"],["2",ar?"المستوى 2 · بايثون المتقدم":"Level 2 · Advanced Python",ar?"قيد التعلم":"In progress"],["🔒",ar?"المستوى 3 · تطوير الألعاب":"Level 3 · Game Development",ar?"مقفل":"Locked"],["🔒",ar?"المستوى 4 · بايثون المتقدم":"Level 4 · Advanced Python",ar?"مقفل":"Locked"]];return <div className="ref-content ref-pad"><div className="ref-between"><Avatar/><div><h2>{ar?"مساري التعليمي":"My Learning Path"}</h2><button className="ref-select">{ar?"مسار بايثون":"Python Track"}⌄</button></div></div><div className="ref-tabs"><b>{ar?"المستويات":"Levels"}</b><span>{ar?"الدورات":"Courses"}</span><span>{ar?"الإنجازات":"Achievements"}</span></div><div className="ref-levels">{levels.map((l,i)=><div className={`ref-level l${i}`} key={i}><div className="ref-dot">{l[0]}</div><div><b>{l[1]}</b><small>{i===0?(ar?"12 درس · 3 مشاريع":"12 lessons · 3 projects"):i===1?(ar?"6 / 13 درس":"6 / 13 lessons"):l[2]}</small>{i===1&&<div className="ref-progress"><i/></div>}</div></div>)}</div><div className="ref-card ref-unlock">🔒 <div><b>{ar?"افتح المستويين 3 و4":"Unlock levels 3 & 4"}</b><small>{ar?"اشترك في الباقة القادمة":"Upgrade to continue"}</small></div><Link href="#">{ar?"عرض الباقات":"View plans"} →</Link></div><div className="ref-card ref-next"><small>{ar?"📚 الدرس القادم":"📚 Next lesson"}</small><h3>{ar?"القوائم والمجموعات":"Lists & Sets"}</h3><p>{ar?"اليوم · 5:00 م":"Today · 5:00 PM"}</p><Link className="ref-primary" href={`/prototype/today?lang=${lang}`}>{ar?"انضم للحصة":"Join class"}</Link></div></div>}

function Today({lang}:{lang:"ar"|"en"}){const ar=lang==="ar";return <div className="ref-content ref-pad"><div className="ref-head-row"><Avatar/><div><h2>{ar?"مهامي اليوم":"Today's Mission"}</h2><small>{ar?"الاثنين · 7 سبتمبر 2026":"Monday · Sep 7, 2026"}</small></div>🔔</div><div className="ref-card ref-streak"><b>{ar?"استمر يا يوسف! 🔥":"Keep going, Youssef! 🔥"}</b><span>{ar?"أنت على بعد حصتين من إكمال المستوى 2!":"You're two sessions away from completing Level 2!"}</span></div><div className="ref-card ref-live"><div className="ref-between"><span className="pill-red">● {ar?"حصة مباشرة":"Live class"}</span><small>{ar?"بعد ساعتين":"in 2 hours"}</small></div><h3>{ar?"بايثون المتقدم":"Advanced Python"}</h3><p>{ar?"القوائم والمجموعات · 5:00–6:00 م":"Lists & Sets · 5:00–6:00 PM"}</p><b>{ar?"👨🏻‍🏫 م. أحمد":"👨🏻‍🏫 Mr. Ahmed"}</b><button className="ref-primary">{ar?"الانضمام للحصة":"Join class"}</button></div><h3 className="section-title">{ar?"مهام اليوم":"Today's tasks"}</h3><div className="ref-task"><span>🧩</span><div><b>{ar?"تحدي صغير":"Mini Challenge"}</b><small>{ar?"استخدم القوائم · 15 دقيقة":"Use lists · 15 min"}</small></div><em>XP 30+</em></div><div className="ref-task"><span>🛠️</span><div><b>{ar?"استوديو المشاريع":"Project Studio"}</b><small>{ar?"تابع مشروعك الحالي":"Continue your current project"}</small></div><em>XP 50+</em></div></div>}

function Projects({lang}:{lang:"ar"|"en"}){const ar=lang==="ar";const ps=[["🚀",ar?"مغامرة فضائية":"Space Adventure","Pygame","ref-grad1"],["🖼️",ar?"مصنف الصور الذكي":"Smart Image Classifier","Teachable Machine","ref-grad2"],["🌐",ar?"موقعي الأول":"My First Website","HTML · CSS · JavaScript","ref-grad3"],["🧮",ar?"تطبيق حاسبة":"Calculator App","Python (Tkinter)","ref-grad4"]];return <div className="ref-content ref-pad"><div className="ref-between"><h2>{ar?"مشاريعي":"My Projects"}</h2>⌕</div><div className="ref-tabs"><b>{ar?"الكل":"All"}</b><span>{ar?"قيد العمل":"In progress"}</span><span>{ar?"مكتمل":"Done"}</span></div><div className="ref-projects">{ps.map((p,i)=><div className="ref-project" key={i}><div className={`ref-project-cover ${p[3]}`}>{p[0]} <span>{i===0?"🪐 🚀 🌌":i===1?"✨ 🖼️ 🧠":i===2?"🌐 💻":"🧮"}</span></div><div className="ref-project-info"><div><b>{p[1]}</b><small>{p[2]}</small></div><span className={i===0?"working":"done"}>{i===0?(ar?"قيد العمل":"Working"):(ar?"مكتمل":"Done")}</span><a>{ar?"عرض المشروع":"View project"}</a></div></div>)}</div><button className="ref-navy">+ {ar?"مشروع جديد":"New Project"}</button></div>}

function Parent({lang}:{lang:"ar"|"en"}){const ar=lang==="ar";return <div className="ref-content ref-pad"><div className="ref-between"><Avatar type="girl"/><div><h2>{ar?"لوحة ولي الأمر":"Parent Dashboard"}</h2><button className="ref-select">{ar?"هذا الشهر":"This month"}⌄</button></div></div><div className="ref-card ref-child"><Avatar/><b>{ar?"تقدم يوسف":"Youssef's Progress"}</b><div className="ref-kpis"><div><strong>92%</strong><small>{ar?"نسبة الحضور":"Attendance"}</small></div><div><strong>12h 30m</strong><small>{ar?"وقت التعلم":"Learning time"}</small></div><div><strong>+18%</strong><small>{ar?"نمو المهارات":"Skill growth"}</small></div></div></div><div className="ref-card ref-skills"><h3>{ar?"تطور المهارات":"Skill Growth"}</h3>{[[ar?"التفكير المنطقي":"Logical Thinking",88,6],["Python",64,12],[ar?"حل المشكلات":"Problem Solving",71,9],[ar?"الإبداع":"Creativity",92,4],[ar?"مفاهيم الذكاء":"AI Concepts",35,15]].map(([n,p,d])=><div className="ref-parent-skill" key={String(n)}><span>{n}</span><div><i style={{width:`${p}%`}}/></div><b>{p}%</b><em>↑{d}%</em></div>)}</div><div className="ref-ai">✅ <div><b>{ar?"رؤية الذكاء الاصطناعي":"AI Insight"}</b><p>{ar?"يوسف يظهر إبداعاً عالياً! نرشح تشجيعه بمزيد من مشاريع تطوير الألعاب.":"Youssef shows strong creativity. We recommend more game-development projects."}</p></div></div><div className="ref-card ref-next-goal"><b>{ar?"موعد قادم":"Upcoming"}</b><span>{ar?"إكمال المستوى 2":"Complete Level 2"}</span><small>{ar?"حصتان متبقيتان":"2 sessions left"}</small></div></div>}

function Assessment({lang}:{lang:"ar"|"en"}){const ar=lang==="ar";return <div className="ref-content ref-pad"><div className="ref-between"><div className="ref-logo">3C</div><LangBtn lang={lang}/></div><h2>{ar?"نتعرّف أكثر على طفلك":"Let's get to know your child"}</h2><div className="ref-stepbar"><i/><i/><i/><i/></div><small>{ar?"الخطوة 1 من 4":"Step 1 of 4"}</small><h3>{ar?"ما عمر طفلك؟":"What is your child's age?"}</h3><div className="ref-options"><button>6–8</button><button className="sel">9–12</button><button>13–15</button><button>16–18</button></div><h3>{ar?"ما هي اهتماماته؟":"What are they interested in?"}</h3><div className="ref-interest"><button>🎮<span>{ar?"الألعاب":"Games"}</span></button><button>🤖<span>{ar?"الذكاء والروبوتات":"AI & Robots"}</span></button><button>🌐<span>{ar?"المواقع":"Web"}</span></button><button>📱<span>{ar?"التطبيقات":"Mobile"}</span></button><button>🎨<span>{ar?"التصميم":"Design"}</span></button><button>📊<span>{ar?"البيانات":"Data"}</span></button></div><h3>{ar?"هل يتوفر لدى طفلك جهاز؟":"Do they have a laptop / tablet?"}</h3><div className="ref-options two"><button className="sel">💻 {ar?"نعم":"Yes"}</button><button>📱 {ar?"ليس بعد":"Not yet"}</button></div><Link className="ref-primary" href={`/prototype/profile?lang=${lang}`}>{ar?"التالي":"Next"} →</Link></div>}

function Coach({lang}:{lang:"ar"|"en"}){const ar=lang==="ar";return <div className="ref-content ref-pad"><div className="ref-head-row"><Avatar/><div><h2>{ar?"المساعد الذكي":"AI Coding Coach"}</h2><small>{ar?"يساعدك على الفهم، لا يعطيك الإجابة فقط":"Teaches, not just answers"}</small></div></div><div className="ref-chat"><div className="ai">🤖 {ar?"أهلاً يوسف! أين توقفت في الكود؟":"Hi Youssef! Where are you stuck in the code?"}</div><div className="user">{ar?"اللعبة لا تحسب النقاط بشكل صحيح":"My game isn't counting points correctly."}</div><pre>{`score = 0\nif player_hit:\n    score =+ 10`}</pre><div className="ai">💡 {ar?"قارن بين =+ و +=. أي واحدة تضيف للقيمة الحالية؟":"Compare =+ with +=. Which one adds to the current value?"}</div></div><Link className="ref-primary" href={`/prototype/projects?lang=${lang}`}>{ar?"جرّب الإصلاح":"Try the fix"} →</Link></div>}

export default function ReferenceV3Screen({screen}:{screen:Screen}){
  const q=useSearchParams(); const lang:qLang = q.get("lang")==="en"?"en":"ar"; type qLang="ar"|"en";
  const body=screen==="landing"?<Landing lang={lang}/>:screen==="assessment"?<Assessment lang={lang}/>:screen==="profile"?<Profile lang={lang}/>:screen==="path"?<Path lang={lang}/>:screen==="today"?<Today lang={lang}/>:screen==="projects"?<Projects lang={lang}/>:screen==="parent"?<Parent lang={lang}/>:<Coach lang={lang}/>;
  return <Shell active={screen} lang={lang}>{body}</Shell>
}
